### PR TITLE
Fix/independent decoding

### PR DESCRIPTION
**Pull request by pxp9**
this will try to fix different decodings for different backends

### CODE REVIEW

**Comment by pxp9** [comment]
Got this error

the trait bound `for<'r> <sqlx::MySql as HasArguments<'r>>::Arguments: IntoArguments<'r, sqlx::MySql>` is not satisfied

but the trait bound is indeed satified.

https://docs.rs/sqlx/0.6.3/sqlx/prelude/trait.IntoArguments.html#impl-IntoArguments%3C'q,+%3CMySqlArguments+as+Arguments%3C'q%3E%3E::Database%3E-for-MySqlArguments

**Comment by pxp9** [comment]
> Got this error
> 
> image
> 
> but the trait bound is indeed satified.
> 
> https://docs.rs/sqlx/0.6.3/sqlx/prelude/trait.IntoArguments.html#impl-IntoArguments%3C'q,+%3CMySqlArguments+as+Arguments%3C'q%3E%3E::Database%3E-for-MySqlArguments

Any ideas ?

**Comment by pxp9** [comment]
It is funny because if you delete MySQL trait override functions it compiles but does pass the tests because is not doing what it is supposed to do.

Maybe i will try to delete trait and see what happens.

**Review by ayrat555 — APPROVED** [review]

**Review by ayrat555 — APPROVED** [review]

**Comment by pxp9** [comment]
We should put an issue to the rust compiler or see wtf is happening with that.

if you write it as

```rust
Self::find_task_by_id(...)
```

This fails because it says the trait bounds are not satisfied which is not true as commented here



> Got this error
> 
> image
> 
> but the trait bound is indeed satisfied.
> 
> https://docs.rs/sqlx/0.6.3/sqlx/prelude/trait.IntoArguments.html#impl-IntoArguments%3C'q,+%3CMySqlArguments+as+Arguments%3C'q%3E%3E::Database%3E-for-MySqlArguments
> 
> Any ideas ?

A workaround is using the trait syntax.

```rust
<BackendSqlXMySQL as FangQueryable<MySql>>::find_task_by_id(...)
```

**Pull request merged**
